services:
  - type: web
    name: gencvats-huggingface-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "7860"
