import { expect, test } from "@playwright/test";

const USE_REAL_BACKEND = process.env.E2E_USE_REAL_BACKEND === "true";

const fakeDocxBuffer = Buffer.from(
  "UEsDBAoAAAAAA",
  "base64"
);

test.beforeEach(async ({ page }) => {
  if (USE_REAL_BACKEND) {
    return;
  }

  await page.route("**/enhance-cv", async (route) => {
    const requestBody = route.request().postDataJSON();
    const summary =
      "Polished summary generated by mocked Playwright response for end-to-end testing.";

    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        ...requestBody,
        Personal_Info: {
          ...requestBody.Personal_Info,
          Summary: summary,
        },
      }),
    });
  });

  await page.route("**/generate-docx", async (route) => {
    await route.fulfill({
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": 'attachment; filename="CV_Test_User_English.docx"',
      },
      body: fakeDocxBuffer,
    });
  });
});

test("user can fill builder flow, enhance CV, and download DOCX", async ({ page }) => {
  await page.goto("/builder");

  await page.getByPlaceholder("Contoh: Budi Santoso").fill("Test User");
  await page.getByPlaceholder("email@domain.com").fill("test.user@example.com");
  await page.getByPlaceholder("+62 812...").fill("081234567890");
  await page.getByPlaceholder("Kota / Kabupaten").fill("Jakarta");
  await page.getByPlaceholder("linkedin.com/in/username").fill("linkedin.com/in/testuser");
  await page
    .getByPlaceholder("github.com/username / portfolio link")
    .fill("https://portfolio.example.com");
  await page.getByRole("button", { name: "Next" }).click();

  await page.getByRole("button", { name: "Manual Input" }).click();
  await page.getByPlaceholder("Universitas Indonesia").fill("Institut Teknologi Bandung");
  await page.getByPlaceholder("Teknik Informatika").fill("Sistem dan Teknologi Informasi");
  await page.getByPlaceholder("2020").fill("2024");
  await page.getByPlaceholder("S. Kom").fill("S.Tr.Kom");
  await page.getByPlaceholder("Range 0.00 - 4.00").fill("3.91");
  await page
    .getByPlaceholder("Machine Learning, NLP, Data Mining")
    .fill("Machine Learning, Distributed Systems");
  await page.getByRole("button", { name: "Tambah Pendidikan" }).click();
  await expect(page.getByText("Institut Teknologi Bandung")).toBeVisible();
  await page.getByRole("button", { name: "Next" }).click();

  await page
    .getByPlaceholder("Posisi (Data Analyst, Software Engineer, dll)")
    .fill("Data Analyst");
  await page
    .getByPlaceholder("Perusahaan (PT ABC, Startup XYZ)")
    .fill("PT Analitik Nusantara");
  await page.getByPlaceholder("Jan 2020 - Des 2021").fill("Jan 2023 - Des 2024");
  await page.getByPlaceholder("Fulltime, Internship, Freelance").fill("Internship");
  await page
    .getByPlaceholder("Meningkatkan performa sistem sebesar 30%...")
    .fill("- Built dashboards\n- Automated reporting");
  await page.getByRole("button", { name: "Tambah Pengalaman" }).click();
  await expect(page.getByText("PT Analitik Nusantara")).toBeVisible();

  await page.getByRole("button", { name: "Projects" }).click();
  await page.getByPlaceholder("Nama Proyek").fill("Customer Churn Dashboard");
  await page.getByPlaceholder("Role").fill("Data Analyst");
  await page.getByPlaceholder("Tech Stack").fill("Python, SQL, Power BI");
  await page.getByPlaceholder("Deskripsi Proyek").fill("- Built dashboard\n- Presented weekly KPIs");
  await page.getByRole("button", { name: "Tambah Proyek" }).click();
  await expect(page.getByText("Customer Churn Dashboard")).toBeVisible();

  await page.getByRole("button", { name: "Skills" }).click();
  const hardSkills = page.getByPlaceholder("Python, SQL, R Language");
  await hardSkills.fill("Python, SQL, Power BI");
  await hardSkills.blur();
  const softSkills = page.getByPlaceholder("Leadership, Team Work, Work Under Pressure");
  await softSkills.fill("Communication, Teamwork, Problem Solving");
  await softSkills.blur();

  await page.getByRole("button", { name: "Next" }).click();

  await page.getByRole("button", { name: "Manual Input" }).click();
  await page.getByRole("combobox").selectOption("Keahlian");
  await page.getByPlaceholder("Nama Sertifikat / Lomba").fill("Google Data Analytics");
  await page.getByPlaceholder("Penerbit / Penyelenggara").fill("Google");
  await page.getByPlaceholder("Tahun").fill("2024");
  await page.getByRole("button", { name: "Tambahkan Manual" }).click();
  await expect(page.getByText("Google Data Analytics")).toBeVisible();
  await page.getByRole("button", { name: "Next" }).click();

  await page.getByRole("button", { name: "Polish & Rewrite with AI" }).click();
  await expect(page.getByText("Enhance selesai")).toBeVisible();
  await page.getByRole("button", { name: "Selesai" }).click();

  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download Result (.docx)" }).click();
  const download = await downloadPromise;

  expect(download.suggestedFilename()).toContain(".docx");
  await expect(page.getByText("File berhasil dibuat")).toBeVisible();
});
